dist: trusty
sudo: required
language: python
notifications:
  slack:
    on_success: never
    on_failure : never
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
# non python dependencies
before_install:
  - sudo apt-get -qq update
  - wget http://pari.math.u-bordeaux.fr/pub/pari/unix/pari-2.9.2.tar.gz
  - tar xf pari-2.9.2.tar.gz
  - cd pari-2.9.2/
  - ./Configure --prefix=/usr/
  - make gp
  - sudo make install
  - cd ..
# command to install dependencies
install: 
  - pip install Cython
  - pip install cysignals --verbose
  - pip install .
# command to run tests
script:
  - cd tests
  - python rundoctest.py

