dist: trusty
sudo: required
language: python
notifications:
  slack:
    on_success: never
    on_failure : never
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
env:
  - PARI_VERSION=pari-2.8.1.beta
    URLDIR=unstable
  - PARI_VERSION=pari-2.9.3
    URLDIR=unix
  - PARI_VERSION=snapshot
    URLDIR=snapshots

before_install:
  - export LC_ALL=C  # Test that this doesn't break Unicode
  - export PATH="/usr/lib/ccache:$PATH"
  - ccache -M 256M && ccache -s
install:
  - bash -x .travis-install-pari.sh
  - pip install --build=/tmp/pip --verbose -r requirements.txt
  - pip install --verbose .
# command to run tests
script:
  - make check
  - (cd docs && make html)
cache:
  directories:
    - $HOME/.ccache
